name: 'copyFiles'
descriptions: 'Uses the composite action to copy and set up files'

# inputs:
#   name:
#     description: 'A name to include in the greeting'

runs:
  using: "composite"
  steps:
    - name: Greet someone
      run: echo "Hello"
      shell: bash